[background-color="#01303a"]
== Understanding conflict resolution

=== Different kinds of conflicts

* Version conflicts
** 2 or more dependencies want a different version of the same thing
* Implementation conflicts
** there are more than one implementation of the same thing

=== Definition of version conflict

There's a _version_ conflict whenever two components:

- depend on the same module D
- depend on different versions of module D

For example:

- A -> D:1.0
- B -> D:1.1

=== Maven vs Gradle

[ditaa, "asciidoctor-diagram-conflict1", height=20%]
....

+------+       +-----------+
|      | ----> |guava:20.0 |
|      |       +-----------+
| root |
|      |       +-----------+        +--------------------+
|      | ----> |guice:4.2.2| -----> | guava:25.1-android |
+------+       +-----------+        +--------------------+
....

* Maven selects version *20.0*
* Gradle selects version *25.1-android*

Why?

=== Maven's Nearest first

* "Nearest" dependency version wins
* `root` -> `guava:20.0` which is _closer_ than `root` -> `guice` -> `guava:25.1-android`
* So `20.0` _wins_

=== Problems with nearest first

=== Nearest is order dependent!

[ditaa, "asciidoctor-diagram-maven1", height=30%]
....

+------+   1    +-------------+      +--------------------+
|      | ---->  | guice:4.2.2 | ---> | guava:25.1-android |
|      |        +-------------+      +--------------------+
| root |
|      |   2    +---------------------+       +----------+
|      | ---->  | reflections:0.9.11  |  ---> | guava:20 |
+------+        +---------------------+       +----------+

....

Selects `guava:25.1-android`

=== Nearest is order dependent!

[ditaa, "asciidoctor-diagram-maven2", height=30%]
....

+------+   1    +---------------------+       +----------+
|      | ---->  | reflections:0.9.11  |  ---> | guava:20 |
|      |        +---------------------+       +----------+
| root |
|      |   2    +-------------+      +--------------------+
|      | ---->  | guice:4.2.2 | ---> | guava:25.1-android |
+------+        +-------------+      +--------------------+

....

Selects `guava:20`

*Nearest first is basically unpredictable for any reasonably sized dependency graph*

=== Typical Maven workarounds

* Adding `exclusions` + first level dependency
** leaks dependencies
* Adding a `dependencyManagement` block
** but non transitive!

=== How Gradle works

* Performs _full conflict resolution_
* All opinions matter
* _Highest wins_: we always choose 25.1-android whatever the order

=== Gradle dependency constraints

```
dependencies {
   constraints {
      implementation("com.google.guava:guava:guava:25.1-android")
   }
}
```

are honored _transitively_

=== Ivy conflict resolution

- Ivy uses _pluggable_ conflict resolvers
- can be different _per dependency_
- hard to reason about

[background-color="#01303a"]
== Handling conflict resolution in Gradle

=== Failing on version conflict

```
configurations {
   compileClasspath {
       resolutionStrategy.failOnVersionConflict()
   }
}
```

- Forces you to _think_ about conflicts
- Requires an explicit way to select a version

=== Dependency resolution rules

* Offer _one_ way to solve conflicts
* Limited to the _configuration being resolved_

```groovy
configurations.all {
    resolutionStrategy.eachDependency {
        if (requested.group == "org.apache.commons" &&
            requested.name == "commons-lang3") {
            useVersion("3.3.1")
            because("tested with this version")
        }
    }
}
```